--------------------------------------------------------
--  Ref Constraints for Table BLOG
--------------------------------------------------------

  ALTER TABLE "MEDIUM_FINAL"."BLOG" ADD CONSTRAINT "BLOG_DOMAIN_FK" FOREIGN KEY ("DOMAIN_DOMAIN_ID")
	  REFERENCES "MEDIUM_FINAL"."DOMAIN" ("DOMAIN_ID") ENABLE;
  ALTER TABLE "MEDIUM_FINAL"."BLOG" ADD CONSTRAINT "BLOG_USER" FOREIGN KEY ("USERS_USERNAME")
	  REFERENCES "MEDIUM_FINAL"."USER_DETAILS" ("USERS_USERNAME") ON DELETE SET NULL ENABLE;
