--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "MEDIUM_FINAL"."COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDIUM_FINAL"."COMMENTS" MODIFY ("date" NOT NULL ENABLE);
  ALTER TABLE "MEDIUM_FINAL"."COMMENTS" MODIFY ("APPROVED" NOT NULL ENABLE);
  ALTER TABLE "MEDIUM_FINAL"."COMMENTS" MODIFY ("BLOG_BLOG_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDIUM_FINAL"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MEDIUM_FINAL"."COMMENTS" MODIFY ("COMMENTATOR" NOT NULL ENABLE);
